services:
  - type: web
    name: auto-data-profiler-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_NAME
        value: Auto Data Profiler
      - key: APP_VERSION
        value: 0.1.0
      - key: DEBUG
        value: false
